name: "Install Nix"
description: "Helper action for installing Nix"

inputs:
  dogfood:
    description: "Whether to dogfood the latest version of the installer"
    default: false
  dogfood-path:
    description: "Path to the local `nix-installer` binary root"
    required: false
  use-cache:
    description: "Whether to cache paths in /nix/store"
    default: true
  no-init:
    description: "Whether to install Nix without init system integration"
    default: false
  cachix-authtoken:
    description: "cachix authentication token"
    default: ""

runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
      with:
        determinate: false

        backtrace: ${{ inputs.dogfood == 'true' && 'full' || '' }}
        local-root: ${{ inputs.dogfood == 'true' && inputs.dogfood-path || '' }}
        log-directives: ${{ inputs.dogfood == 'true' && 'nix_installer=debug' || '' }}
        logger: ${{ inputs.dogfood == 'true' && 'pretty' || '' }}

        init: ${{ inputs.no-init == 'true' && 'none' || '' }}
        planner: ${{ inputs.no-init == 'true' && 'linux' || '' }}

    - uses: cachix/cachix-action@v15
      with:
        name: nix-installer
        authToken: "${{ inputs.cachix-authtoken}}"
